### ISSUE TITLE
Gestures

### ISSUE THREAD

**Issue by jruesga** [jruesga/CMFileManager#8]
Add gestures like swipe to delete

**Comment by DvTonder** [comment]
Look at the example of swipe to delete here -> https://plus.google.com/photos/113735310430199015092/albums/5802529880018632993/5802529911679028882 and contextual undo here -> https://plus.google.com/photos/113735310430199015092/albums/5802529880018632993/5802529923333076770

**Comment by jruesga** [comment]
I have two question
- When you confirm the deletion of the file or folder?
- Do you like the image of teh contextual button for #11?

**Comment by DvTonder** [comment]
I'm not sure I understand your first question - looking at the delete confirmation dialog, it shows "QUESTION" in the title with the stop/question mark icon.  The android design guidelines actually recommend not using an icon in the title of a dialog box unless in has a special meaning.  It can be removed from this dialog box (and probably most of them).  

The title should not be "QUESTION" but should say "Confirm delete".  We should look at all the dialog boxes and ensure their titles are appropriate to the action.

**Comment by jruesga** [comment]
What i'm saying is that to have an undo action is too complicated here, because there are a phisycal delete of the object. To do this, it's necessary to createa recycle bin. Appart of this, also it's needed a confirmation of the user prior to do this operation.

**Comment by DvTonder** [comment]
Ah, OK. I had not thought about the complexity of doing undo.  Just swipe to delete would be OK - but there should still be a confirmation dialog

**Comment by jruesga** [comment]
Done. David, could you test it?

**Comment by DvTonder** [comment]
OK, tested it.  The slide gesture works OK but the single click and long-click is inconsistent now.  Clicking into folders only works about 20% of the time, long-click is the same.

**Comment by jruesga** [comment]
I have no side effects here. It works 100% for click and long-click in i9100. Could you put an eye in FlingerListView#onTouchEvent method to see what is wrong in your device?

**Comment by DvTonder** [comment]
I am doing a full, clean build and will test again after flashing

**Comment by DvTonder** [comment]
Problem still persists.  There are also related issues for example when I start swiping horizontally, I can swipe vertically at the same time and scroll up and down.  Up down scrolling should be disabled when the horizontal swipe has started.  

Click and long-click does not work for me 90% of the time.  I will run a debug build later today.

**Comment by DvTonder** [comment]
Also, some times, when scrolling up, if I am moving my finger slightly to the side, one of the items in the list starts the drag to delete.  Its not always the one under my finger but could be further down in the list.
